project_id = "rwdjasxvkupweowgrrwl"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
